apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: everything-staging
  name: everything-staging
  namespace: everything-staging
spec:
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: dotnetcoresdk:latest
  output:
    to:
      kind: ImageStreamTag
      name: 'everything-staging:v1.0.0'
  resources: {}
  runPolicy: Serial
  source:
    git: 
      uri: https://github.com/jfsvak/everything.git
      ref: master
    contextDir: "backend-app/src"
  triggers:
    - type: GitHub
      github:
        secretReference:
          name: everything-staging-master-pullrequest
    - type: imageChange
      imageChange: {}
  postCommit: {}
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 2
