apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: everything-staging
  name: everything-staging
  namespace: everything-staging
spec:
  replicas: 1
  selector:
    app: everything-staging
    deploymentconfig: everything-staging
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: everything-staging
        deploymentconfig: everything-staging
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Openshift
            - name: EVErything_App_Connection
              value: server=mysql-57-centos7.everything-dev.svc;user=everything_app;password=password;database=everything_app
            - name: EVErything_Identity_Connection
              value: server=mysql-57-centos7.everything-dev.svc;user=everything_identity;password=password;database=everything_identity
            - name: EVE_CLIENT_ID
              value: d5e93faa39cf4db781cfd3b425d4993c
            - name: EVE_SECRET_KEY
              value: lNUDDifxO5E0HSDXTVgP1rPNe1MrKJ4gQe0Q9rU7
            - name: ESI_CALLBACK_URL
              value: http://everything-staging.192.168.99.100.nip.io/esicallback
          image: 172.30.1.1:5000/everything-staging/everything-staging
          imagePullPolicy: Always
          name: everything-staging
          resources: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - everything-staging
        from:
          kind: ImageStreamTag
          name: 'everything-staging:v1.0.0'
          namespace: everything-staging
  revisionHistoryLimit: 3