apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: everything-staging
  name: everything-staging
  namespace: everything-staging
spec:
  lookupPolicy:
    local: false

---

apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: everything-staging
  name: everything-staging
  namespace: everything-staging
spec:
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: dotnetcoresdk:latest
        namespace: general-stuff
  output:
    to:
      kind: ImageStreamTag
      name: 'everything-staging:v1.0.0'
  resources: {}
  runPolicy: Serial
  source:
    git: 
      uri: https://github.com/jfsvak/everything.git
      ref: master
    contextDir: "backend-app/src"
  triggers:
    - type: imageChange
      imageChange: {}
  postCommit: {}
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 2

---

apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: everything-staging
  name: everything-staging
  namespace: everything-staging
spec:
  replicas: 1
  selector:
    app: everything-staging
    deploymentconfig: everything-staging
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: everything-staging
        deploymentconfig: everything-staging
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: EVErything_App_Connection
              value: server=mysql-57-centos7.everything-staging.svc;user=everything_app;password=password;database=everything_app
            - name: EVErything_Identity_Connection
              value: server=mysql-57-centos7.everything-staging.svc;user=everything_identity;password=password;database=everything_identity
            - name: EVE_CLIENT_ID
              value: 574efdaa56ec417f918a9f9d86d7c437
            - name: EVE_SECRET_KEY
              value: wRnhfvCP84nwp8mk95DlsPe9cFxIOCwTaK4PKpgR
            - name: ESI_CALLBACK_URL
              value: http://everything-staging.192.168.99.100.nip.io/esicallback
          image: 172.30.1.1:5000/everything-staging/everything-staging
          imagePullPolicy: Always
          name: everything-staging
          resources: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - everything-staging
        from:
          kind: ImageStreamTag
          name: 'everything-staging:v1.0.0'
          namespace: everything-staging
  revisionHistoryLimit: 3
  
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: everything-staging
  name: everything-staging
  namespace: everything-staging
spec:
  selector:
    app: everything-staging
  ports:
  - name: http-80
    port: 80
    protocol: TCP
    targetPort: 5000
  type: ClusterIP
  
---

apiVersion: v1
kind: Route
metadata:
  labels:
    app: everything-staging
  name: everything-staging
  namespace: everything-staging
spec:
  host: everything-staging.192.168.99.100.nip.io
  to:
    kind: Service
    name: everything-staging
    weight: 100

