kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-data-claim
  namespace: everything-staging
  labels:
    app: mysql-57-centos7
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
 #storageClassName: local-storage

---

apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: mysql-57-centos7
  name: mysql-57-centos7
  namespace: everything-staging
spec:
  replicas: 1
  selector:
    app: mysql-57-centos7
    deploymentconfig: mysql-57-centos7
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: mysql-57-centos7
        deploymentconfig: mysql-57-centos7
    spec:
      containers:
        - name: mysql-57-centos7
          image: centos/mysql-57-centos7
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          volumeMounts:
            - mountPath: /var/lib/mysql/data
              name: mysqldata
      restartPolicy: Always
      volumes:
        - name: mysqldata
          persistentVolumeClaim:
            claimName: mysql-data-claim
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - mysql-57-centos7
        from:
          kind: ImageStreamTag
          name: 'mysql-57-centos7:latest'
          namespace: general-stuff
      type: ImageChange

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-57-centos7
  name: mysql-57-centos7
  namespace: everything-staging
spec:
  ports:
    - name: tcp-3306
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql-57-centos7
    deploymentconfig: mysql-57-centos7
  type: ClusterIP
  