apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: everything-uiapp-dev
  name: everything-uiapp-dev
  namespace: everything-dev
spec:
  lookupPolicy:
    local: false


---

apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: everything-uiapp-dev
  name: everything-uiapp-dev
  namespace: everything-dev
spec:
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'nodejs:10'
        namespace: openshift
    type: Source
  output:
    to:
      kind: ImageStreamTag
      name: 'everything-uiapp-dev:latest'
  runPolicy: Serial
  source:
    binary: {}
    type: Binary

---

apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: everything-uiapp-dev
  name: everything-uiapp-dev
  namespace: everything-dev
spec:
  replicas: 1
  selector:
    deploymentconfig: everything-uiapp-dev
  strategy:
    type: Rolling
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
  template:
    metadata:
      labels:
        app: everything-uiapp-dev
        deploymentconfig: everything-uiapp-dev
    spec:
      containers:
        - name: everything-uiapp-dev
          image: 172.30.1.1:5000/everything-dev/everything-uiapp-dev
          env:
            - name: NPM_RUN
              value: server
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - everything-uiapp-dev
        from:
          kind: ImageStreamTag
          name: 'everything-uiapp-dev:latest'
          namespace: everything-dev


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: everything-uiapp-dev
  name: everything-uiapp-dev
  namespace: everything-dev
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 3000
  selector:
    deploymentconfig: everything-uiapp-dev
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: v1
kind: Route
metadata:
  labels:
    app: everything-uiapp-dev
  name: everything-uiapp-dev
  namespace: everything-dev
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: everything-uiapp-dev
    weight: 100