apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: everything-dev
  name: everything-dev
  namespace: everything-dev
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: '172.30.1.1:5000/everything-dev/everything-dev'
  tags:
    - items:
        - created: '2019-06-08T09:22:54Z'
          dockerImageReference: >-
            172.30.1.1:5000/everything-dev/everything-dev@sha256:636832482d95b93b0d1061792979e65b36f6367fba5d42bfc91e2f25b22bbc8c
          generation: 1
          image: >-
            sha256:636832482d95b93b0d1061792979e65b36f6367fba5d42bfc91e2f25b22bbc8c
        - created: '2019-06-08T08:54:08Z'
          dockerImageReference: >-
            172.30.1.1:5000/everything-dev/everything-dev@sha256:886d23162301809cc79eb17fee9e064d7b3a7c890dbb05bb6823a4d5fbce1d27
          generation: 1
          image: >-
            sha256:886d23162301809cc79eb17fee9e064d7b3a7c890dbb05bb6823a4d5fbce1d27
      tag: latest

---

apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: everything-dev
  name: everything-dev
  namespace: everything-dev
spec:
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: '172.30.124.220:5000/openshift/dotnetsdk:latest'
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: 'everything-dev:latest'
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  triggers:
    - generic:
        secret: r-B5FqyBPkmiowAWbiFx
      type: Generic
  postCommit: {}
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 3

---

apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: everything-dev
  name: everything-dev
  namespace: everything-dev
spec:
  replicas: 1
  selector:
    app: everything-dev
    deploymentconfig: everything-dev
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: everything-dev
        deploymentconfig: everything-dev
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Openshift
            - name: EVErything_App_Connection
              value: server=mysql-57-centos7.everything-dev.svc;user=everything_app;password=password;database=everything_app
            - name: EVErything_Identity_Connection
              value: server=mysql-57-centos7.everything-dev.svc;user=everything_identity;password=password;database=everything_identity
            - name: EVE_CLIENT_ID
              value: d5e93faa39cf4db781cfd3b425d4993c
            - name: EVE_SECRET_KEY
              value: lNUDDifxO5E0HSDXTVgP1rPNe1MrKJ4gQe0Q9rU7
            - name: ESI_CALLBACK_URL
              value: http://everything-dev.192.168.99.100.nip.io/esicallback
          image: 172.30.1.1:5000/everything-dev/everything-dev
          imagePullPolicy: Always
          name: everything-dev
          resources: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - everything-dev
        from:
          kind: ImageStreamTag
          name: 'everything-dev:latest'
          namespace: everything-dev
  revisionHistoryLimit: 3

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: everything-dev
  name: everything-dev
  namespace: everything-dev
spec:
  selector:
    app: everything-dev
  ports:
  - name: http-80
    port: 80
    protocol: TCP
    targetPort: 5000
  type: ClusterIP
  
---

apiVersion: v1
kind: Route
metadata:
  labels:
    app: everything-dev
  name: everything-dev
  namespace: everything-dev
spec:
  host: everything-dev.192.168.99.100.nip.io
  to:
    kind: Service
    name: everything-dev
    weight: 100
