kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
 storageClassName: local-storage
 selector:
   name: mysql-data

---

apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: mysql-57-centos7
  name: mysql-57-centos7
  namespace: everything-dev
spec:
  selector:
    app: mysql-57-centos7
    deploymentconfig: mysql-57-centos7
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: mysql-57-centos7
        deploymentconfig: mysql-57-centos7
    spec:
      containers:
        - name: mysql-57-centos7
          image: >-
            centos/mysql-57-centos7@sha256:8d750876687d9fb0adf46020e38cd43165b906208d2e81088b3a13213e751df3
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          volumeMounts:
            - mountPath: /var/lib/mysql/data
              name: mysqldata
      restartPolicy: Always
      volumes:
        - name: mysqldata
          persistentVolumeClaim:
            claimName: mysql-data-claim
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - mysql-57-centos7
        from:
          kind: ImageStreamTag
          name: 'mysql-57-centos7:latest'
          namespace: everything-dev
        lastTriggeredImage: >-
          centos/mysql-57-centos7@sha256:8d750876687d9fb0adf46020e38cd43165b906208d2e81088b3a13213e751df3
      type: ImageChange

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-57-centos7
  name: mysql-57-centos7
  namespace: everything-dev
spec:
  ports:
    - name: tcp-3306
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql-57-centos7
    deploymentconfig: mysql-57-centos7
  type: ClusterIP
  